plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
	id "maven-publish"
}

mossyDependencies {
	minecraft = stonecutter.current.project.substring(stonecutter.current.project.indexOf("-") + 1)
	lombok = prop("base.lombok_version")

	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	forge = prop("build.forge")

	neoForge = prop("build.neoforge")
	parchment = prop("build.parchment")

	additional {
		//disable("oldpotions")

		if (stonecutter.current.version.startsWith("26.1")) {
			disable("mossylib")
			disable("inventory-particles")
		} else {
			if (sc.current.project.contains("fabric")) {
				override("modRuntimeOnly", "mossylib")
			} else {
				override("runtimeOnly", "mossylib")
			}
		}


	}
}

repositories {
	mavenLocal()
	maven {
		name "Mossy Projects"
		url "https://maven.lopymine.net/releases"
	}
}

dependencies {
	def oldPotions = prop("dep.oldpotions")
	if (oldPotions != "unknown") {
		implementation group: 'com.electronwill.night-config', name: 'toml', version: '3.6.7'
	}

	def project = stonecutter.current.project
	if (project.contains("26.1")) {
		implementation("net.lopymine:mossylib:1.1.0-fabric-26.1-pre-2")
		implementation("net.lopymine:inventory_particles:1.5.0-fabric-26.1-pre-2")
	}
}

stonecutter {
	replacements.string(current.parsed >= "1.21.11") {
		replace("ResourceLocation", "Identifier")
		replace(".location()", ".identifier()")
	}
}

String prop(String key) {
	return findProperty(key).toString()
}