plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
	id "maven-publish"
}

mossyDependencies {
	minecraft = stonecutter.current.project.substring(stonecutter.current.project.indexOf("-") + 1)
	lombok = prop("base.lombok_version")

	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	forge = prop("build.forge")

	neoForge = prop("build.neoforge")
	parchment = prop("build.parchment")

	additional {
		//disable("oldpotions")

		override("mossyRuntimeOnly", "mossylib")
		override("mossyCompileOnly", "inventory-particles")
	}
}

repositories {
	mavenLocal()
	maven {
		name "Mossy Projects"
		url "https://maven.lopymine.net/releases"
	}
}

dependencies {
	def oldPotions = prop("dep.oldpotions")
	if (oldPotions != "unknown") {
		implementation group: 'com.electronwill.night-config', name: 'toml', version: '3.6.7'
	}
}

stonecutter {
	replacements.string(current.parsed >= "1.21.11") {
		replace("ResourceLocation", "Identifier")
		replace(".location()", ".identifier()")
	}
}

String prop(String key) {
	return findProperty(key).toString()
}