# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.152.2+26.2

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.2&l=fabric
dep.modmenu=20.0.0-beta.3
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.2&l=fabric
dep.yacl=3.9.4+26.2-fabric
# oldpotions, check https://modrinth.com/mod/oldpotions/versions?g=26.2&l=fabric
dep.oldpotions=unknown
# mossylib, check https://modrinth.com/mod/mossylib/versions?g=26.2&l=fabric
dep.mossylib=1.5.0+26.2+fabric
# inventory-particles, check https://modrinth.com/mod/inventory-particles/versions?g=26.2&l=fabric
dep.inventory-particles=2.4.0+26.1+fabric
